language: node_js

node_js:
  - "8"
  - "10"
  - "12"

install:
  - npm i
  - npm i ts-node # --require ts-node/register

before_script:
  - npm run lint
  - npm run build

script:
  - npm run test
  - npm run cov
  - npm run clean
