environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '9'
    - nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i ts-node

test_script:
  - node --version
  - npm --version
  - set DEBUG=xmind-sdk:* npm run test
  - npm run build

build: off
