environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '9'
    - nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i ts-node
  - npm i npminstall && node_modules\.bin\npminstall

test_script:
  - node --version
  - npm --version
  - npm run test
  - npm run build

build: off
